### ISSUE TITLE
Verifying MCXN947 E thernet + DHCP

### ISSUE THREAD

**Issue by ehughes** [wavenumber-eng/mcxn-iot#1]
Setup this repo/west manifest as normal:

**1.) project setup**

`west init -m https://github.com/wavenumber-eng/mcxn-iot --mr main`

(the readme.me was copied from another project, but is mostly correct)

**2.)   build**

There is a sample in samples/dhcpv4_client

This was just a copy of the sample in the zephyr samples/net folder except that I added the ozone config.

This sample will trying to get an ipaddress from your router.   It worked ok on mine.    We can use this to test your setup.

**Build as normal:**

`west build -b frdm_mcxn947/mcxn947/cpu0 --pristine`

3.)   test/Demo

here you can see it waiting for the DHCP server in the router to return an ip.     

I then to a DNS query to get google's IP and then ping.

Note:  most of the time, your router will have DNS setup by default.

I then ping the MCXN board from my computer.

![mcxn_iot](https://github.com/user-attachments/assets/045b7513-8960-4635-9163-7df62ba34a2f)

This should get you setup for ethernet testing.

**Comment by jerpa77** [comment]
It was an ethernet cable problem (:
Working well now :D

**Comment by ehughes** [comment]
good news!
