### ISSUE TITLE
Add Golioth

### ISSUE THREAD

**Issue by ehughes** [wavenumber-eng/mcxn-iot#2]
Please add golioth to this west file.    See if you can get a demo project working with FRDM-MCXN947

Important note:

To get the FRDM-MCXN947 to build w/ golioth, you need to add these to the board kconfig overlay:

CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

ie.e.   create an board overlay in the example simliar to these:
https://github.com/golioth/golioth-firmware-sdk/tree/main/examples/zephyr/hello/boards

You can move a copy of the hello sample in this repository (mcxn-iot).

**Comment by ehughes** [comment]
@jerpa77 

I know we were having troubles with this project last week.      I want to post information to the golioth website.  However,  I would like to you quickly try something

In the main west.yml,    please reference  golioth v0.14 instead of "main".

This is what they mention on their github..

![image](https://github.com/user-attachments/assets/28053c56-7f23-4e80-a1c0-446157414b1b)

1.)  Please repeat the hello test with native sim.    If it fails, please capture a .gif

2.)  Please try using the MCXN947 board as well.  If it fails/crashes,  capture an animated gif.

Please spend an hour or two on this.  I just want to see of v0.14 behaves differently.

**Comment by jerpa77** [comment]
Ok, that's what I got with Golioth revision V0.14.0

# native_sim

#### DHCPv4_client sample
![image](https://github.com/user-attachments/assets/b227dec3-26fc-4d5b-8daa-a18c5475f7cd)

#### Hello sample
![image](https://github.com/user-attachments/assets/27e11f4b-8e9b-4faf-8633-705cc2e254ee)
![image](https://github.com/user-attachments/assets/c9703494-f66a-4757-80b2-6ac0fa6252b3)

**Comment by jerpa77** [comment]
# FRDM-MCXN947

#### Hello sample
![image](https://github.com/user-attachments/assets/8745c478-93b6-4e97-8fc1-fad84571e0b1)
![image](https://github.com/user-attachments/assets/ca500de8-65cb-4384-be7e-f6653b83789a)
- The program crashes after the `net dns` command execution


#### DHCPV4_client + Golioth Sample
![image](https://github.com/user-attachments/assets/000e3259-c984-46d3-9f88-e5dc26c2a0bd)

- The program crashes after the `net dns` command execution
- If the golioth client is not created, the net dns command works well

**Comment by jerpa77** [comment]
I also tried moving changing the Zephyr version to 3.6.0
But it didn't work as well...
![image](https://github.com/user-attachments/assets/8360b955-c5cd-4a8e-b45e-db5260bc8b68)


I'm not pretty sure If I'm doing something wrong
