### ISSUE TITLE
Segger SystemView Test Project

### ISSUE THREAD

**Issue by ehughes** [wavenumber-eng/mcxn-iot#3]
@jerpa77 

An NXP customer was requesting some help with setting up Segger SystemView.   The are using the i.MXRT1176,  but we can test with any Zephyr board (FRDM-MCXN947)

SystemView is a free tool that works with the j-link.    It can you thread usage, etc. graphically.  It can send the tracing data over RTT

https://www.segger.com/products/development-tools/systemview/

See the section SEGGER SystemView Support 

https://docs.zephyrproject.org/latest/services/tracing/index.html

![image](https://github.com/user-attachments/assets/7c708993-646d-4246-8db8-01dfc9f009c7)

Please set up a new project in the "applications" folder.   Make it a copy of the "basic_synchronization" sample reference is the zephyr documentation.

See if you can get it working.

I don't think it is needed for systemview,  but   you can enable zephyr "awareness"  in the ozone project:

https://wiki.segger.com/Zephyr_RTOS_awareness_in_Ozone

This is the proj.conf they used.  

![image](https://github.com/user-attachments/assets/75570485-d056-4edd-b4a6-0a0b2c89813a)

Once you get this working, please make some simple setup instructions.

**Comment by jerpa77** [comment]
Done, here is the link of the project

https://github.com/wavenumber-eng/mcxn-iot/tree/main/applications/synchronization
